### ISSUE TITLE
Permissions wrong after install

### ISSUE THREAD

**Issue by has207** [AnyChart/gjstags#3]
Running sudo make install on Linux (ubuntu 10.04) installs the binaries with root:root and 0640, i.e. not readable or executable by normal users

**Comment by batsuev** [comment]
Thank you for report. Will check soon.

**Comment by batsuev** [comment]
Please pull and check. Fixed in https://github.com/AnyChart/gjstags/commit/63cf5b34f0f8bcacb437d1add749e37cabdced04
