### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by ghost** [AnyChart/gjstags#5]
~/source/gjstags/ make
mkdir -p classes
mkdir -p bin
/usr/java/latest/bin/javac -sourcepath src -classpath libs/compiler.jar -d classes src/com/anychart/gjstags/CommandLineRunner.java
src/com/anychart/gjstags/ctags/CTag.java:49: error: illegal start of expression
    public void writeCTagString(Writer writer) throws IOException {
    ^
src/com/anychart/gjstags/ctags/CTag.java:49: error: illegal start of expression
    public void writeCTagString(Writer writer) throws IOException {
           ^
src/com/anychart/gjstags/ctags/CTag.java:49: error: ';' expected
    public void writeCTagString(Writer writer) throws IOException {
                               ^
src/com/anychart/gjstags/ctags/CTag.java:49: error: ';' expected
    public void writeCTagString(Writer writer) throws IOException {
                                             ^
src/com/anychart/gjstags/ctags/CTag.java:49: error: not a statement
    public void writeCTagString(Writer writer) throws IOException {
                                                      ^
src/com/anychart/gjstags/ctags/CTag.java:49: error: ';' expected
    public void writeCTagString(Writer writer) throws IOException {
                                                                 ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: illegal start of expression
    public static CTag fromString(String line) {
    ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: illegal start of expression
    public static CTag fromString(String line) {
           ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: ';' expected
    public static CTag fromString(String line) {
                      ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: ')' expected
    public static CTag fromString(String line) {
                                        ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: illegal start of expression
    public static CTag fromString(String line) {
                                             ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: ';' expected
    public static CTag fromString(String line) {
                                              ^
src/com/anychart/gjstags/ctags/CTag.java:59: error: cannot find symbol
    public static CTag fromString(String line) {
                                  ^
  symbol:   variable String
  location: class CTag
src/com/anychart/gjstags/ctags/CTag.java:61: error: cannot find symbol
        String tag = line;
                     ^
  symbol:   variable line
  location: class CTag
src/com/anychart/gjstags/ctags/CTag.java:64: error: cannot find symbol
            tag = line.substring(0, tag.indexOf(";\"\t"));
                  ^
  symbol:   variable line
  location: class CTag
src/com/anychart/gjstags/ctags/CTag.java:65: error: cannot find symbol
            meta = line.substring(tag.indexOf(";\"\t"));
                   ^
  symbol:   variable line
  location: class CTag
src/com/anychart/gjstags/ctags/CTag.java:80: error: incompatible types
        return res;
               ^
  required: String
  found:    CTag
src/com/anychart/gjstags/ctags/CTagsFile.java:66: error: cannot find symbol
            tag.writeCTagString(writer);
               ^
  symbol:   method writeCTagString(BufferedWriter)
  location: variable tag of type CTag
src/com/anychart/gjstags/ctags/CTagsFile.java:76: error: cannot find symbol
            CTag tag = CTag.fromString(line);
                           ^
  symbol:   method fromString(String)
  location: class CTag
19 errors
make: **\* [compile] Error 1

/usr/java/latest/bin/javac -version
javac 1.7.0_05

uname -r
3.4.3-1.fc17.x86_64

**Comment by batsuev** [comment]
Thanks, will try to reproduce and report soon

**Comment by DisDis** [comment]
Fixed this issue:

diff --git a/configure b/configure
index e6d5a57..cc6a394 100755
--- a/configure
+++ b/configure
@@ -19,7 +19,7 @@ JAVAC=javac
 JAR=jar

 options=$@
-arguments=($options)
+arguments=$options
 index=0
 for argument in $options
   do
diff --git a/src/com/anychart/gjstags/ctags/CTag.java b/src/com/anychart/gjstags
index 17b41cc..161d5f6 100644
--- a/src/com/anychart/gjstags/ctags/CTag.java
+++ b/src/com/anychart/gjstags/ctags/CTag.java
@@ -45,7 +45,7 @@ public class CTag {

```
 public String getCTagString() {
     return this.getName() + "\t" + this.getFile() + "\t" + this.getAddress(
```

## 
-    }

**Comment by jonlesser** [comment]
DisDis's diff worked for me. The formatting is messed up in the comment above. The two changes are:

1) in the configure file, change ($options) to $options.
2) In src/com/anychart/gjstags/ctags/CTag.java the getCTagString function needs a closing curly brace.

**Comment by ghost** [comment]
worked for me as well.
